name: Maven test

on:
  push:
  workflow_dispatch:

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Clone DBSQLite
        uses: actions/checkout@v4
        with:
          ref: 'develop'
          repository: 'armand0w/DBSQLite'
          path: DBSQLite
        run: mvn --batch-mode -f DBSQLite/pom.xml -DskipTests install -e -B

      - name: Clone TgBotApi
        uses: actions/checkout@v4
        with:
          ref: 'develop'
          repository: 'armand0w/tgBotApi'
          path: tgBotApi
        run: mvn --batch-mode -f tgBotApi/pom.xml -DskipTests install -e -B

      - name: Build
        run: mvn --batch-mode -DskipTests -e -B package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true -e -B test
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          USER_ID: ${{ secrets.USER_ID }}

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
