name: Maven test

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Java 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'
          cache: maven

      - name: Clone DBSQLite
        uses: actions/checkout@v4
        with:
          ref: 'develop'
          repository: 'armand0w/DBSQLite'
          path: DBSQLite

      - name: Clone TgBotApi
        uses: actions/checkout@v4
        with:
          ref: 'develop'
          repository: 'armand0w/TgBotApi'
          path: TgBotApi

      - name: Storing config
        run: echo "${{ secrets.CONFIG }}" | base64 --decode > config.json

      - name: Set TZ
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "America/Mexico_City"

      - name: Build
        run: |
          mvn -f DBSQLite/pom.xml -DskipTests install -e -B
          mvn -f TgBotApi/pom.xml -DskipTests install -e -B
          mvn -DskipTests -e -B package

      - name: Test
        run: mvn test -Dmaven.test.failure.ignore=true -e -B
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          USER_ID: ${{ secrets.USER_ID }}
          TZ: America/Mexico_City

      - name: Report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
